// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXvzQexMiomVJvVZuWmzxpuSxHNtU9OIc',
    appId: '1:536698210907:web:b9c35cfeffbce710ea0d7e',
    messagingSenderId: '536698210907',
    projectId: 'myprojr-dbd86',
    authDomain: 'myprojr-dbd86.firebaseapp.com',
    storageBucket: 'myprojr-dbd86.appspot.com',
    measurementId: 'G-PMJMM1HZKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOkG4VG0hY_RxRtJ7hxlbpoRHllDRTqHU',
    appId: '1:536698210907:android:15a758454f51bc27ea0d7e',
    messagingSenderId: '536698210907',
    projectId: 'myprojr-dbd86',
    storageBucket: 'myprojr-dbd86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLGm_ak_VONLTblWMxateIwAuXu4MkYMs',
    appId: '1:536698210907:ios:5412131be8be7e4fea0d7e',
    messagingSenderId: '536698210907',
    projectId: 'myprojr-dbd86',
    storageBucket: 'myprojr-dbd86.appspot.com',
    iosBundleId: 'com.example.mylogin191',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLGm_ak_VONLTblWMxateIwAuXu4MkYMs',
    appId: '1:536698210907:ios:5412131be8be7e4fea0d7e',
    messagingSenderId: '536698210907',
    projectId: 'myprojr-dbd86',
    storageBucket: 'myprojr-dbd86.appspot.com',
    iosBundleId: 'com.example.mylogin191',
  );
}
